# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0007_unicode_literals'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageattachment',
            name='front_view',
            field=models.BooleanField(default=False, verbose_name='Use as front view image in rack'),
        ),
    ]
